site_name: Clinikal documentation
nav:
    - Welcome to Clinikal: Welcome to Clinikal.md
    - Get started:
          - Docker installation: get_started/docker_installation.md
          - Manual installation: get_started/openemr_modules.md
          - Documents storage: get_started/documents_storage.md
          - Internationalization: get_started/internationalization.md
          - Set up a first clinic: get_started/setup_first_clinic.md
    - API refference:
        - Clinikal: api/clinikal.md
        - FHIR: api/fhir.md
    - License: license.md
theme: readthedocs