site_name: Clinikal documentation
nav:
    - Welcome to Clinikal: Welcome to Clinikal.md
    - Get started:
          - Docker installation: get_started/docker_installation.md
          - OpenEMR modules: get_started/openemr_modules.md
          - Documents storage: get_started/documents_storage.md
          - Internationalization: get_started/Internationalization.md
          - Set up a first clinic: get_started/setup_first_clinic.md
    - API:
        - Clinikal: api/clinikal.md
        - FHIR: api/fhir.md
theme: readthedocs
