site_name: Clinikal documentation
nav:
    - Welcome to Clinikal: Welcome to Clinikal.md
    - Get started:
          - Docker installation: get_started/docker_installation.md
          - Manual installation: get_started/openemr_modules.md
          - Documents storage: get_started/documents_storage.md
          - Internationalization: get_started/internationalization.md
          - Set up a first clinic: get_started/setup_first_clinic.md
    - API refference:
        - FHIR: api/fhir.md
        - Clinikal: api/clinikal.md
    - Developers guide:
          - JS libraries: technical_details/client_side_libraries.md
          - Assets components: technical_details/assets_components.md
          - Production architecture: technical_details/architecture.md
    - License: license.md
theme: readthedocs